baseURL = 'https://kollihills.co.in'
languageCode = 'en-us'
title = 'Kolli Hills - One Stop Travel Guide'
enableGitInfo = true
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
[params]
  author = 'iAvian Private Limited'
  description = "Kolli Hills - Your guide to explore Kolli Hills"
  footer_company = "iAvian Private Limited"
  footer_date = "© 2024"
  footer_href = "https://iavian.com"
